apiVersion : apps/v1
kind: Deployment
metadata:
    name: edge 
    namespace: acubed
    labels:
      app: edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge
  template:
    metadata:
      labels:
        app: edge 
    spec:
      containers:
        - name: edge 
          image: edge
          imagePullPolicy: Never
          ports:
          - containerPort: 80
